### PR TITLE
init new lib

### PR DESCRIPTION
**Pull request by arkwave**
Initializing a new folder for the infoFlow translations.

### CODE REVIEW

**Comment by Christopher-Tennant** [comment]
Moving forward!

**Comment by AceHao** [comment]
[Solved]are we making a new folder called infoflow?

**Comment by stefanv** [comment]
Why this folder?  And why the PEP8 incompatible name :)

**Comment by Christopher-Tennant** [comment]
Hi Stefan, We are adding another transfer entropy application. It is very streamlined, has a GNU license, and will provide additional utility beyond the 'evenflow' transfer entropy application. We are changing the name to be PEP8 compatible! :)

**Comment by stefanv** [comment]
Can you expand a bit? Is this an external library? What license is
involved, and what are the repercussions of that?

**Comment by Christopher-Tennant** [comment]
This is another implementation that computes transfer entropy It is a much shorter routine that will allow us to compare estimates of transfer entropy for data series from both toolboxes. This series of codes is much more transparent giving us better insights into the functionality of the algorithms. Much of the code was translated into Python during today's work session. All of the codes are "free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version." The full toolbox can be found here: https://physionet.org/physiotools/tewp/

**Pull request merged**
