### PR TITLE
Create infoflow

### PR DESCRIPTION
**Pull request by Christopher-Tennant**
Renamed InfoFlow to infoflow/

### CODE REVIEW

**Comment by arkwave** [comment]
is this pull request for renaming the folder?

**Comment by Christopher-Tennant** [comment]
Yep

On Tuesday, April 19, 2016, Ananth Ravi Kumar notifications@github.com
wrote:

> is this pull request for renaming the folder?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/machine-shop/evenflow/pull/30#issuecomment-212270732

## 

---

Christopher J Tennant, PhD
Postdoctoral Researcher,
Environmental Systems Dynamics Laboratory http://www.esdlberkeley.com/
UC Berkeley, Dept. of Geography
Tennant Research Webpage

## https://sites.google.com/site/christopherjtennanthomepage/home

**Comment by arkwave** [comment]
there are a bunch of merge conflicts that need to be resolved before the pull request can be approved

**Comment by Christopher-Tennant** [comment]
Closing this pull request. 'infoflow' folder has been created. 'InfoFlow' needs to be removed.

**Pull request closed without merging**
